### ISSUE TITLE
Material browser, doesn't show anything on the window

### ISSUE THREAD

**Issue by Reddbr34** [xblah-software/modding-tool#13]
![image](https://github.com/jean-knapp/xblah-modding-tool-public/assets/47085253/f3962fe9-b2e2-48db-bc94-7125ed93fc9a)

**Comment by jean-knapp** [comment]
What game, tool edition and version are you using?

**Comment by Reddbr34** [comment]
Source SDK 2013 singleplayer. Happened with the previous and current version. Happens with any texture browser on the program. (material dashboard or the texture browser for the model editor)

**Comment by jean-knapp** [comment]
if you have an up to date version, there could be an issue with the mod's game info. Are you using the Essentials Edition or Advanced Edition?

You can get in touch in discord too, I can answer you faster there.

**Comment by Reddbr34** [comment]
Advanced edition, nothing changed with gameinfo, and it was working before, it just stopped.

**Comment by GuestSneezeOSDev** [comment]
what are your specs?

**Comment by jean-knapp** [comment]
Fixed in latest update.
