### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [xblah-software/modding-tool#17]

**Comment by jean-knapp** [comment]
I can share specific parts of it if you wanna know how anything works, but as for the whole tool, I can't.

**Comment by GuestSneezeOSDev** [comment]
if its a colsed source app why is it on github?

**Comment by jean-knapp** [comment]
> if its a colsed source app why is it on github?

Github allows private repositories. And I use it for version control, branching, rolling back changes, etc.

**Comment by Vincent392** [comment]
> I can share specific parts of it if you wanna know how anything works, but as for the whole tool, I can't. 

What parts can you open source?

**Comment by jean-knapp** [comment]
> > I can share specific parts of it if you wanna know how anything works, but as for the whole tool, I can't.
> 
> What parts can you open source?

What do you want to see?
