### ISSUE TITLE
Library Client?

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [xblah-software/modding-tool#18]
i got an issue saying that it could not find a library module

**Comment by GuestSneezeOSDev** [comment]
<img width="295" alt="Screenshot 2024-06-22 210610" src="https://github.com/xblah-software/modding-tool/assets/163439609/96053eec-f4e5-46fb-9c67-7f0cdcceab2c">

**Comment by jean-knapp** [comment]
You need to compile your own binary for that mod template.
